### ISSUE TITLE
Error: svelte-scrolling doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module

### ISSUE THREAD

**Issue by partiallywritten** [valmisson/svelte-scrolling#4]
Hey @valmisson thanks for this awesome plugin! However, after updating this plugin from `1.1.1` to `1.2.0` I'm getting this error.

**Error:** `
svelte-scrolling doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.`
**Version:**
 - svelte-scrolling: `1.2.0`
 - svelte-kit: `1.0.0-next.348`

**Comment by valmisson** [comment]
Thanks for reporting, this issue has been fixed in [v1.2.1](https://github.com/valmisson/svelte-scrolling/compare/v1.2.0...v1.2.1)
