### ISSUE TITLE
Demo broke in REPL ('default' is not exported)

### ISSUE THREAD

**Issue by oneezy** [valmisson/svelte-scrolling#5]
There appears to be an error in your code that's not allowing me to see a demo in Svelte [REPL](https://svelte.dev/repl/ef46aaaa519548faa05aef83ba95dd43?version=3.48.0)
```
'default' is not exported by https://unpkg.com/svelte@3/store/index.mjs, imported by https://unpkg.com/svelte-scrolling@1.2.1/dist/store/index.js
```
https://svelte.dev/repl/ef46aaaa519548faa05aef83ba95dd43?version=3.48.0

**Comment by valmisson** [comment]
Thanks for reporting this issue. A fix was sent in v1.2.2.
