### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by sjess** [valmisson/svelte-scrolling#7]
```
exports is not defined
ReferenceError: exports is not defined
    at /node_modules/svelte-scrolling/dist/index.js:5:23
```

Using SvelteKit with Vite, clean project with TS.

svelte.dev/repl shows

`'default' is not exported by https://unpkg.com/svelte@3/store/index.mjs, imported by https://unpkg.com/svelte-scrolling@1.2.1/dist/store/index.js`

**Comment by valmisson** [comment]
Thanks for reporting this issue. A fix was sent in v1.2.2.
