### ISSUE TITLE
Scroll to by ID

### ISSUE THREAD

**Issue by cloudlena** [valmisson/svelte-scrolling#8]
Intuitively, scrolling to is done by the `id` HTML property. It would be nice if, instead of having to work with `scrollRef`, I could just use an ID (e.g. by using `use:scrollTo={'#people'}`). I need to set the ID anyway because I want people to be able to create a link like domain.com#people so having to set an additional `use:scrollRef` seems a bit redundant.

Many other similar libraries work with that (e.g. https://github.com/langbamit/svelte-scrollto).

I'm imagining something like this

```svelte
<nav>
  <a use:scrollTo={'#people'}>People</a>
</nav>

<div id="people">
  ...
</div>
```

This could even fix a warning I'm currently getting with this library from the Svelte A11y plugin: `A11y: <a> element should have an href attribute`

So, I could do something like:

```svelte
<a href="#people" use:scrollTo={'#people'}>People</a>
```

which would also increase the accessibility of this library.

**Comment by stevesob** [comment]
This is easy with vanilla JS. I have a page that I scroll like an airline
schedule board. Use scrollIntoView() and set CSS to smooth.

await tick()
await delay(6000)
let nitems = items.length
for (let i = 0; i < nitems; i++) {
let item = "item" + (i + 1)
let el = document.getElementById(item)
//console.log("sob-- ~ getData ~ el", el, item)
await delay(2000)
el.scrollIntoView()
await tick()
if (i == nitems - 1) {
i = 0
document.getElementById("top").scrollIntoView()
await delay(6000)
}
}
.sob-content {
padding-top: 50px;
padding-bottom: 100%;
scroll-behavior: smooth;
}

*Steven Olensky*

**Comment by cloudlena** [comment]
:+1: Thanks, @stevesob!
